"""Single-universe DMX output over an OpenDMX-style FTDI cable.

Runs a background thread that emits a 512-channel frame at ~40 Hz.
Fixtures register with the universe and write to their channel slice;
the next frame the sender thread sends picks up the new values.

BREAK is generated by the baud-rate-switch trick (write 0x00 at 90000
baud = ~111us low pulse — well above the 88us DMX minimum). This avoids
pyserial's break_condition + time.sleep, which is too imprecise on
macOS for stricter fixtures.
"""

from __future__ import annotations

import threading
import time

import serial


class Universe:
    """One DMX universe.

    If `mock=True` (or the serial port can't be opened) the sender thread
    runs but doesn't write to any hardware — the channel array is still
    updated, so the rest of the app works for visualization / dev.
    """

    def __init__(self, port: str, fps: int = 30, mock: bool = False) -> None:
        self.port = port
        self.period = 1.0 / fps
        self.mock = mock
        self._channels = bytearray(512)
        self._lock = threading.Lock()
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        self._ser: serial.Serial | None = None
        self._error: BaseException | None = None

    # ----- lifecycle -----

    def start(self) -> None:
        if not self.mock:
            try:
                self._ser = serial.Serial(
                    port=self.port,
                    baudrate=250_000,
                    bytesize=serial.EIGHTBITS,
                    parity=serial.PARITY_NONE,
                    stopbits=serial.STOPBITS_TWO,
                    timeout=0,
                    write_timeout=2,
                )
            except serial.SerialException as e:
                print(f"[dmx-tx] serial port unavailable ({e}); falling back to mock mode")
                self.mock = True
                self._ser = None
        self._stop.clear()
        self._thread = threading.Thread(target=self._run, daemon=True, name="dmx-tx")
        self._thread.start()

    def stop(self, blackout: bool = True) -> None:
        if blackout:
            with self._lock:
                self._channels[:] = b"\x00" * 512
            time.sleep(self.period * 2)  # let the sender push the blackout
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=2)
            self._thread = None
        if self._ser is not None:
            self._ser.close()
            self._ser = None

    def __enter__(self) -> "Universe":
        self.start()
        return self

    def __exit__(self, *exc: object) -> None:
        self.stop()

    # ----- channel access -----

    def set_range(self, start_address: int, values: bytes | bytearray) -> None:
        i = start_address - 1
        with self._lock:
            self._channels[i : i + len(values)] = values

    def set_channel(self, address: int, value: int) -> None:
        with self._lock:
            self._channels[address - 1] = value & 0xFF

    def add(self, *fixtures: "Fixture") -> None:
        for f in fixtures:
            f.attach(self)

    # ----- internals -----

    def _run(self) -> None:
        next_tick = time.monotonic()
        try:
            while not self._stop.is_set():
                if not self.mock:
                    with self._lock:
                        snapshot = bytes(self._channels)
                    self._send(snapshot)
                next_tick += self.period
                sleep = next_tick - time.monotonic()
                if sleep > 0:
                    time.sleep(sleep)
                else:
                    next_tick = time.monotonic()  # we fell behind, resync
        except BaseException as e:  # surface silent thread crashes
            self._error = e
            print(f"[dmx-tx] sender thread died: {e!r}")

    def _send(self, channels: bytes) -> None:
        ser = self._ser
        if ser is None:
            return
        ser.baudrate = 90_000
        ser.write(b"\x00")  # ~111us low = DMX BREAK
        ser.flush()
        ser.baudrate = 250_000
        ser.write(b"\x00" + channels)  # start code + 512 channels
        ser.flush()


class Fixture:
    """Base class. Subclass and set CHANNELS to a tuple of channel names."""

    CHANNELS: tuple[str, ...] = ()

    def __init__(self, start_address: int, name: str | None = None) -> None:
        if not self.CHANNELS:
            raise TypeError(f"{type(self).__name__} must define CHANNELS")
        self.start_address = start_address
        self.name = name or f"{type(self).__name__}@{start_address}"
        self._values = bytearray(len(self.CHANNELS))
        self._universe: Universe | None = None

    @property
    def end_address(self) -> int:
        return self.start_address + len(self.CHANNELS) - 1

    def attach(self, universe: Universe) -> None:
        self._universe = universe
        self._push()

    def dump(self) -> str:
        lines = [f"{self.name}  (DMX {self.start_address}..{self.end_address}):"]
        for i, role in enumerate(self.CHANNELS):
            dmx_ch = self.start_address + i
            lines.append(f"  DMX {dmx_ch:3d}  ch{i + 1} ({role:<7s}) = {self._values[i]}")
        return "\n".join(lines)

    def _set(self, channel_name: str, value: int) -> None:
        idx = self.CHANNELS.index(channel_name)
        self._values[idx] = max(0, min(255, int(value)))
        self._push()

    def _set_many(self, **kwargs: int) -> None:
        for name, value in kwargs.items():
            idx = self.CHANNELS.index(name)
            self._values[idx] = max(0, min(255, int(value)))
        self._push()

    def _push(self) -> None:
        if self._universe is not None:
            self._universe.set_range(self.start_address, bytes(self._values))

    def __repr__(self) -> str:
        return f"<{self.name} addr={self.start_address}-{self.end_address}>"
